config/routes.rb
# frozen_string_literal: true

##
# = routes.rb
# Author::    Mushaka Solutions
# Copyright:: Copyright 2018-2019 Mushaka Solutions Inc.
# License::   GNU Public License 3
#
# Routes for the application
Rails.application.routes.draw do
  # Clearance routes to constrains signed in users to the dashboard
  constraints Clearance::Constraints::SignedIn.new do
    root to: 'dashboard#show', as: :signed_in_root
  end

  # Clearance routes to constrain signed out users to the public pages
  constraints Clearance::Constraints::SignedOut.new do
    root to: 'public#index'
  end

  # Clearance routes for users and passwords for password resets
  resources :users, controller: 'users', only: [:create] do
    resource :password, controller: 'clearance/passwords',
                        only: %i[create edit update]
  end

  # Clearance routes for passwords
  resources :passwords, controller: 'clearance/passwords', only: %i[create new]

  # Clearance routes for login
  resource :session, controller: 'sessions', only: %i[create new]

  # Application route for dashboard
  get 'dashboard', to: 'dashboard#show', as: :dashboard

  # Application routes for bookings
  resources :bookings, only: %i[index show new create edit update destroy]

  # Application routes for clients
  resources :clients, only: %i[index show new create edit update destroy]

  # Application routes for package groups
  resources :package_groups, only: %i[index new create edit update destroy] do
    # Application routes for packages
    resources :packages, only: %i[new create show edit update destroy]
  end

  # Application routes for booking requests
  resources :booking_requests, only: %i[new show create edit update destroy] do
    member do
      post 'confirm'
    end
  end

  # Application route for public pricing
  get 'pricing', to: 'public#pricing', as: :pricing

  # The root application route
  root 'public#index'
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

##
# = DashboardController
# Author::    Richard Davis
# Copyright:: Copyright 2018-2019 Mushaka Solutions Inc.
# License::   GNU Public License 3
#
# This controller provides methods for accessing the dashboard as well as
# any associated actions.
class DashboardController < ApplicationController
  before_action :require_login

  ##
  # GET /dashboard
  def show
    @booking_requests = BookingRequest.all
  end

  private

  ##
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
  end
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

##
# = DashboardHelper
# Author::    Richard Davis
# Copyright:: Copyright 2018-2019 Mushaka Solutions
# License::   GNU Public License 3
#
# This controller provides helper methods for dashboard views.
module DashboardHelper
end

app/views/dashboard/show.html.haml
.jumbotron
  %h1.text-center Booking Requests
.container-fluid
  - if @booking_requests.count > 0
    .grid
      .grid-sizer
        - @booking_requests.each do |br|
          .card
            .card-body
              %h3.card-title.text-center= "#{format_date(br.requested_date)} at #{format_time(br.requested_time)}"
              %hr
              %h4.card-title Client Information
              %p.card-text= "#{br.first_name} #{br.last_name}"
              %p.card-text
                %span.text-muted Email:
                = br.email
              %p.card-text
                %span.text-muted Phone:
                = br.phone_number
              %hr
              %h4.card-title Package Information
              %p.card-text
                %span.text-muted Package:
                = br.package.name
              %p.card-text
                %span.text-muted Total Cost:
                = number_to_currency(br.package.total_cost)
              %p.card-text
                %span.text-muted Retainer Fee:
                = number_to_currency(br.package.retainer_fee)
              .text-center
                .btn-group.btn-group-lg{ role: 'group' }
                  = button_to confirm_booking_request_path(br), class: 'btn btn-success btn-lg mt-2', method: 'post'  do
                    %i{ class: 'fa fa-check' }
                    \Confirm
                  = button_to booking_request_path(br), class: 'btn btn-danger btn-lg mt-2', method: 'delete', 'data-toggle': 'tooltip', 'data-placement': 'bottom', title: 'Delete this booking request', data: { confirm: 'Are you sure?' } do
                    %i{ class: 'fa fa-times' }
                    \Delete
  - else
    .row.justify-content-center
      .col-md-6
        .text-center
          .alert.alert-info There are currently no booking requests for review.
:javascript
  document.addEventListener('turbolinks:load', function() {
    let grid = document.querySelector('.grid');

    let msnry = new Masonry( grid, {
      itemSelector: '.grid-item',
      columnWidth: '.grid-sizer',
      percentPosition: true,
      gutter: 10
    });
  }, false);