config/routes.rb
# frozen_string_literal: true

##
# = routes.rb
# Author::    Mushaka Solutions
# Copyright:: Copyright 2018-2019 Mushaka Solutions Inc.
# License::   GNU Public License 3
#
# Routes for the application
Rails.application.routes.draw do
  # Clearance routes to constrains signed in users to the dashboard
  constraints Clearance::Constraints::SignedIn.new do
    root to: 'dashboard#show', as: :signed_in_root
  end

  # Clearance routes to constrain signed out users to the public pages
  constraints Clearance::Constraints::SignedOut.new do
    root to: 'public#index'
  end

  # Clearance routes for users and passwords for password resets
  resources :users, controller: 'users', only: [:create] do
    resource :password, controller: 'clearance/passwords',
                        only: %i[create edit update]
  end

  # Clearance routes for passwords
  resources :passwords, controller: 'clearance/passwords', only: %i[create new]

  # Clearance routes for login
  resource :session, controller: 'sessions', only: %i[create new]

  # Application route for dashboard
  get 'dashboard', to: 'dashboard#show', as: :dashboard

  # Application routes for bookings
  resources :bookings, only: %i[index show new create edit update destroy]

  # Application routes for clients
  resources :clients, only: %i[index show new create edit update destroy]

  # Application routes for package groups
  resources :package_groups, only: %i[index new create edit update destroy] do
    # Application routes for packages
    resources :packages, only: %i[new create show edit update destroy]
  end

  # Application routes for booking requests
  resources :booking_requests, only: %i[new show create edit update destroy] do
    member do
      post 'confirm'
    end
  end

  # Application route for public pricing
  get 'pricing', to: 'public#pricing', as: :pricing

  # The root application route
  root 'public#index'
end

app/models/booking.rb
# frozen_string_literal: true

##
# = Booking
# Author::    Richard Davis
# Copyright:: Copyright 2018-2019 Mushaka Solutions Inc.
# License::   GNU Public License 3
#
# This controller provides validations and methods for the booking model.
class Booking < ApplicationRecord
  belongs_to :client
  belongs_to :booking_package

  validates :name, presence: true
  validates :start_date, presence: true
  validates :start_time, presence: true
  validates :client_id, presence: true
  validates :booking_package_id, presence: true
end

app/controllers/bookings_controller.rb
# frozen_string_literal: true

##
# = BookingsController
# Author::    Richard Davis
# Copyright:: Copyright 2018-2019 Mushaka Solutions
# License::   GNU Public License 3
#
# This controller provides methods for accessing booking resources.
class BookingsController < ApplicationController
  before_action :require_login
  before_action :set_booking, only: %i[show edit update destroy]

  ##
  # GET /bookings
  def index
    @bookings = if params[:client_id]
                  Booking.where('client_id = ?', params[:client_id])
                else
                  Booking.all
                end
  end

  ##
  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  ##
  # GET /bookings/:booking_id
  def show; end

  ##
  # GET /bookings/:booking_id/edit
  def edit; end

  ##
  # POST /bookings
  def create
    @booking = Booking.create(booking_from_params)

    if @booking.save
      redirect_to booking_path(@booking), notice: t('notices.booking.create')
    else
      @booking.booking_package.destroy
      redirect_to new_booking_path, alert: @booking.errors.full_messages
    end
  end

  ##
  # PATCH/PUT /bookings/:booking_id
  def update
    if @booking.update(booking_params)
      redirect_to booking_path(@booking), notice: t('notices.booking.update')
    else
      redirect_to edit_booking_path(@booking), alert: @booking.errors.full_messages
    end
  end

  ##
  # DELETE /bookings/:booking_id
  def destroy
    @booking.destroy
    redirect_to bookings_path, notice: t('notices.booking.destroy')
  end

  private

  ##
  # Sets booking for individual resource actions
  def set_booking
    @booking = Booking.find(params[:id])
  end

  ##
  # Archives a package as a booking package
  def archive_package(package_id)
    package = Package.find(package_id)
    BookingPackage.create(name: package.name,
                          duration: package.duration,
                          retainer_fee: package.retainer_fee,
                          total_cost: package.total_cost)
  end

  def booking_from_params
    {
      name: booking_params[:name],
      start_date: booking_params[:start_date],
      start_time: booking_params[:start_time],
      client: Client.find(booking_params[:client_id]),
      booking_package: archive_package(booking_params[:booking_package])
    }
  end
  ##
  # Whitelists parameters
  def booking_params
    params.require(:booking).permit(:name, :start_date, :start_time, :client_id, :booking_package)
  end
end

app/helpers/bookings_helper.rb
# frozen_string_literal: true

##
# = BookingsHelper
# Author::    Richard Davis
# Copyright:: Copyright 2018-2019 Mushaka Solutions
# License::   GNU Public License 3
#
# This controller provides helper methods for booking views.
module BookingsHelper
end

app/views/bookings/_form.html.haml
= form_for @booking do |f|
  .form
    .form-group
      = f.label :name
      = f.text_field :name
    .form-group
      = f.label :start_date
      = f.date_field :start_date, start_year: DateTime.now.year, end_year: (DateTime.now.year + 4)
    .form-group
      = f.label :start_time
      = f.time_field :start_time
    .form-group
      = f.label :client
      = f.collection_select :client_id, Client.all, :id, ->(client){"#{client.first_name} #{client.last_name}"}
      %small{ id: 'clientHelp', class: 'text-muted' }
        = link_to 'Client not listed?', new_client_path
    .form-group
      = f.label :package
      = f.collection_select :booking_package, format_packages(PackageGroup.all), :id, ->(package){"#{package.name} | #{number_to_currency(package.total_cost, unit: '$')}"}
      %small{ id: 'packageHelp', class: 'text-muted' }
        = link_to 'Package not listed?', package_groups_path
    .form-action
      = f.submit 'Save', class: 'BookingCard__button_solid'
      %input{ value: 'Back', type: 'button', method: 'get', class: 'BookingCard__button_outline', onclick: 'history.back()'}

app/views/bookings/edit.html.haml
.BookingCard
  .BookingCard__card-body_rounded
    %h3= I18n.t('pages.bookings.edit.title')
    = render 'form'

app/views/bookings/index.html.haml
.BookingsRibbon
  = button_to I18n.t('pages.bookings.index.action-ribbon.create'), new_booking_path, method: 'get', class: 'BookingsRibbon__button_solid'
%hr
.BookingsContainer
  - if @bookings.count > 0
    - @bookings.each do |booking|
      .BookingsCard.BookingsContainer__grid-item
        .BookingsCard__card-header
          .BookingsIconPanel
            = link_to booking_path(booking), class: 'BookingsIconPanel__icon-link'  do
              %i{ class: 'fa fa-eye fa-2x BookingsIconPanel__icon-link_view', title: I18n.t('pages.bookings.index.icon-panel.view'), 'aria-hidden': 'true' }
            = link_to edit_booking_path(booking), class: 'BookingsIconPanel__icon-link' do
              %i{ class: 'fa fa-pencil fa-2x BookingsIconPanel__icon-link_edit', title: I18n.t('pages.bookings.index.icon-panel.edit'), 'aria-hidden': 'true' }
            = link_to booking_path(booking), class: 'BookingsIconPanel__icon-link', method: 'delete', data: { confirm: 'Are you sure?' } do
              %i{ class: 'fa fa-trash fa-2x BookingsIconPanel__icon-link_delete', title: I18n.t('pages.bookings.index.icon-panel.delete'), 'aria-hidden': 'true' }
        .BookingsCard__card-body_rounded-bottom
          %h3= link_to "#{booking.client.first_name} #{booking.client.last_name}", client_path(booking.client)
          %p.text-centered
            %span.text-muted= "#{format_date(booking.start_date)} at #{format_time(booking.start_time)}"
          %p
            %span.text-muted= "#{I18n.t('models.booking_package.fields.duration')}:"
            = booking.booking_package.duration
            %span.text-muted mins
          %p
            %span.text-muted= "#{I18n.t('models.booking_package.fields.name')}:"
            = booking.booking_package.name
          %p
            %span.text-muted= "#{I18n.t('models.booking_package.fields.total_cost')}:"
            = number_to_currency(booking.booking_package.total_cost)
          %p
            %span.text-muted= "#{I18n.t('models.booking_package.fields.retainer_fee')}:"
            = number_to_currency(booking.booking_package.retainer_fee)
  - elsif @bookings.count == 0 && params[:client_id]
    .BookingsCard.BookingsContainer__grid-item_single
      .BookingsCard__card-body_rounded
        %h3= I18n.t('pages.bookings.index.messages.no-bookings-for-client.heading')
        %p= I18n.t('pages.bookings.index.messages.no-bookings-for-client.text')
  - else
    .BookingsCard.BookingsContainer__grid-item_single
      .BookingsCard__card-body_rounded
        %h3= I18n.t('pages.bookings.index.messages.no-bookings.heading')
        %p= I18n.t('pages.bookings.index.messages.no-bookings.text')

app/views/bookings/new.html.haml
.BookingCard
  .BookingCard__card-body_rounded
    %h3= I18n.t('pages.bookings.new.title')
    = render 'form'

app/views/bookings/show.html.haml
.BookingCard
  .BookingCard__card-header
    .BookingIconPanel
      = link_to edit_booking_path(@booking), class: 'BookingIconPanel__icon-link' do
        %i{ class: 'fa fa-pencil fa-2x BookingIconPanel__icon-link_edit', title: 'Edit this booking', 'aria-hidden': 'true' }
      = link_to booking_path(@booking), method: 'delete', class: 'BookingIconPanel__icon-link', title: 'Delete this booking', data: { confirm: 'Are you sure?' } do
        %i{ class: 'fa fa-trash fa-2x BookingIconPanel__icon-link_delete', 'aria-hidden': 'true' }
  .BookingCard__card-body_not-rounded
    %h3= @booking.name
    %h4 Client Information
    %p
      %span= link_to "#{@booking.client.first_name} #{@booking.client.last_name}", client_path(@booking.client)
    %p
      %span.text-muted Email:
      = @booking.client.email
    %p
      %span.text-muted Phone:
      = @booking.client.phone_number
    %h4 Booking Details
    %p
      %span.text-muted Package:
      = @booking.booking_package.name
    %p
      %span.text-muted Scheduled date:
      = "#{format_date(@booking.start_date)} at #{format_time(@booking.start_time)}"
    %p
      %span.text-muted Duration:
      = @booking.booking_package.duration
      %span.text-muted mins
    %p
      %span.text-muted Total cost:
      = number_to_currency(@booking.booking_package.total_cost)
    %p
      %span.text-muted Retainer fee:
      = number_to_currency(@booking.booking_package.retainer_fee)
  .BookingCard__card-footer
    = link_to 'Back to Bookings', bookings_path, method: 'get'