config/routes.rb
# frozen_string_literal: true

##
# = routes.rb
# Author::    Mushaka Solutions
# Copyright:: Copyright 2018-2019 Mushaka Solutions Inc.
# License::   GNU Public License 3
#
# Routes for the application
Rails.application.routes.draw do
  # Clearance routes to constrains signed in users to the dashboard
  constraints Clearance::Constraints::SignedIn.new do
    root to: 'dashboard#show', as: :signed_in_root
  end

  # Clearance routes to constrain signed out users to the public pages
  constraints Clearance::Constraints::SignedOut.new do
    root to: 'public#index'
  end

  # Clearance routes for users and passwords for password resets
  resources :users, controller: 'users', only: [:create] do
    resource :password, controller: 'clearance/passwords',
                        only: %i[create edit update]
  end

  # Clearance routes for passwords
  resources :passwords, controller: 'clearance/passwords', only: %i[create new]

  # Clearance routes for login
  resource :session, controller: 'sessions', only: %i[create new]

  # Application route for dashboard
  get 'dashboard', to: 'dashboard#show', as: :dashboard

  # Application routes for bookings
  resources :bookings, only: %i[index show new create edit update destroy]

  # Application routes for clients
  resources :clients, only: %i[index show new create edit update destroy]

  # Application routes for package groups
  resources :package_groups, only: %i[index new create edit update destroy] do
    # Application routes for packages
    resources :packages, only: %i[new create show edit update destroy]
  end

  # Application routes for booking requests
  resources :booking_requests, only: %i[new show create edit update destroy] do
    member do
      post 'confirm'
    end
  end

  # Application route for public pricing
  get 'pricing', to: 'public#pricing', as: :pricing

  # The root application route
  root 'public#index'
end

app/models/package_group.rb
# frozen_string_literal: true

##
# = PackageGroup
# Author::    Richard Davis
# Copyright:: Copyright 2018-2019 Mushaka Solutions Inc.
# License::   GNU Public License 3
#
# This controller provides validations and methods for the package groups model.
#
# Package group and package resources share a nested, one-to-many relationship.
class PackageGroup < ApplicationRecord
  has_many :packages, dependent: :destroy

  validates :name, presence: true, length: { maximum: 75 }
  validates :description, length: { maximum: 256 }
end

app/controllers/package_groups_controller.rb
# frozen_string_literal: true

##
# = PackageGroupsController
# Author::    Richard Davis
# Copyright:: Copyright 2018-2019 Mushaka Solutions Inc.
# License::   GNU Public License 3
#
# This controller provides methods for accessing package group resources.
#
# Package groups have many packages.
class PackageGroupsController < ApplicationController
  before_action :require_login
  before_action :set_package_group, only: %i[edit update destroy]

  ##
  # GET /package_groups/new
  def index
    @package_groups = PackageGroup.all
  end

  ##
  # GET /package_groups/new
  def new
    @package_group = PackageGroup.new
  end

  ##
  # GET /package_groups/:package_group/edit
  def edit; end

  ##
  # POST /package_groups
  def create
    @package_group = PackageGroup.create(package_group_params)

    if @package_group.save
      redirect_to package_groups_path, notice: t('notices.package_group.create')
    else
      redirect_to new_package_group_path, alert: @package_group.errors.full_messages
    end
  end

  ##
  # PATCH/PUT /package_groups/:package_group_id
  def update
    if @package_group.update(package_group_params)
      redirect_to package_groups_path, notice: t('notices.package_group.update')
    else
      redirect_to edit_package_group_path(@package_group), alert: @package_group.errors.full_messages
    end
  end

  ##
  # DELETE /package_groups/:package_group_id
  def destroy
    @package_group.destroy
    redirect_to package_groups_path, notice: t('notices.package_group.destroy')
  end

  private

  ##
  # Sets package group for individual resource actions
  def set_package_group
    @package_group = PackageGroup.find(params[:id])
  end

  ##
  # Whitelists parameters
  def package_group_params
    params.require(:package_group).permit(:name, :description)
  end
end

app/helpers/package_groups_helper.rb
# frozen_string_literal: true

##
# = PackageGroupsHelper
# Author::    Richard Davis
# Copyright:: Copyright 2018-2019 Mushaka Solutions
# License::   GNU Public License 3
#
# This controller provides helper methods for package groups views.
module PackageGroupsHelper
  def element_for_pg_item(count)
    return '_triple' if (count % 3).zero?
    return '_double' if (count % 2).zero?
    return '_single' if (count % 1).zero?

    ''
  end
end

app/views/package_groups/_form.html.haml
= form_for @package_group do |f|
  .form
    .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control', placeholder: 'e.g. Weddings'
    .form-group
      = f.label :description
      = f.text_area :description, class: 'form-control', placeholder: 'e.g. Capture one of your most important life moments. From first look to flower toss, your big day is covered. Choose the package that provides the coverage that you need.'
    .form-action
      = f.submit 'Save', class: 'PackageGroupCard__button_solid'
      %input{ value: 'Back', type: 'button', method: 'get', class: 'PackageGroupCard__button_outline', onclick: 'history.back()'}

app/views/package_groups/edit.html.haml
.PackageGroupCard
  .PackageGroupCard__card-body_rounded
    %h3 Edit Package Group
    = render 'form'

app/views/package_groups/index.html.haml
.PackageGroupsRibbon
  = button_to I18n.t('pages.package_groups.index.action-ribbon.create'), new_package_group_path, method: 'get', class: 'PackageGroupsRibbon__button_solid'
%hr
.PackageGroupsContainer
  - if @package_groups.count > 0
    - @package_groups.each do |pg|
      .PackageGroupsContainer__callout.PackageGroupsHero
        .PackageGroupsIconPanel
          = link_to edit_package_group_path(pg), class: 'PackageGroupsIconPanel__icon-link' do
            %i{ class: 'fa fa-pencil fa-2x PackageGroupsIconPanel__icon-link_edit', title: I18n.t('pages.package_groups.index.icon-panel.view') }
          = link_to package_group_path(pg), class: 'PackageGroupsIconPanel__icon-link', method: 'delete', data: { confirm: 'Are you sure?' } do
            %i{ class: 'fa fa-trash fa-2x PackageGroupsIconPanel__icon-link_delete', title: I18n.t('pages.package_groups.index.icon-panel.delete') }
        %h1.PackageGroupsHero__heading= pg.name
        %p.PackageGroupsHero__lead
          - if pg.description != ''
            = pg.description
        = button_to I18n.t('pages.package_groups.index.other.create-package'), new_package_group_package_path(pg), method: 'get', class: 'PackageGroupsHero__button_outline'
      - if pg.packages.count.zero?
        .PackageGroupsContainer__grid-item_single.PackageGroupsCard
          .PackageGroupsCard__card-body_rounded
            %h3= I18n.t('pages.packages.index.messages.no-packages.heading')
            %p.text-centered= I18n.t('pages.packages.index.messages.no-packages.text')
      - else
        - pg.packages.order(total_cost: :asc).each do |package|
          %div{ class: "PackageGroupsContainer__grid-item#{element_for_pg_item(pg.packages.count)} PackageGroupCard" }
            .PackagesCard__card-header
              .PackagesIconPanel
                = link_to package_group_package_path(pg, package), class: 'PackagesIconPanel__icon-link'  do
                  %i{ class: 'fa fa-eye fa-2x PackagesIconPanel__icon-link_view', title: I18n.t('pages.packages.index.icon-panel.view') }
                = link_to edit_package_group_package_path(pg, package), class: 'PackagesIconPanel__icon-link' do
                  %i{ class: 'fa fa-pencil fa-2x PackagesIconPanel__icon-link_edit', title: I18n.t('pages.packages.index.icon-panel.edit') }
                = link_to package_group_package_path(pg, package), class: 'PackagesIconPanel__icon-link', method: 'delete', data: { confirm: 'Are you sure?' } do
                  %i{ class: 'fa fa-trash fa-2x PackagesIconPanel__icon-link_delete', title: I18n.t('pages.packages.index.icon-panel.delete') }
            .PackagesCard__card-body_rounded-bottom
              = render partial: 'packages/package_details', package: package
  - else
    .PackageGroupsContainer__grid-item_single.PackageGroupCard
      .PackageGroupsCard__card-body_rounded
        %h3= t('pages.package_groups.index.messages.no-package-groups.heading')
        %p.text-centered= t('pages.package_groups.index.messages.no-package-groups.text')

app/views/package_groups/new.html.haml
.PackageGroupCard
  .PackageGroupCard__card-body_rounded
    %h3 New Package Group
    = render 'form'