config/routes.rb
# frozen_string_literal: true

##
# = routes.rb
# Author::    Mushaka Solutions
# Copyright:: Copyright 2018-2019 Mushaka Solutions Inc.
# License::   GNU Public License 3
#
# Routes for the application
Rails.application.routes.draw do
  # Clearance routes to constrains signed in users to the dashboard
  constraints Clearance::Constraints::SignedIn.new do
    root to: 'dashboard#show', as: :signed_in_root
  end

  # Clearance routes to constrain signed out users to the public pages
  constraints Clearance::Constraints::SignedOut.new do
    root to: 'public#index'
  end

  # Clearance routes for users and passwords for password resets
  resources :users, controller: 'users', only: [:create] do
    resource :password, controller: 'clearance/passwords',
                        only: %i[create edit update]
  end

  # Clearance routes for passwords
  resources :passwords, controller: 'clearance/passwords', only: %i[create new]

  # Clearance routes for login
  resource :session, controller: 'sessions', only: %i[create new]

  # Application route for dashboard
  get 'dashboard', to: 'dashboard#show', as: :dashboard

  # Application routes for bookings
  resources :bookings, only: %i[index show new create edit update destroy]

  # Application routes for clients
  resources :clients, only: %i[index show new create edit update destroy]

  # Application routes for package groups
  resources :package_groups, only: %i[index new create edit update destroy] do
    # Application routes for packages
    resources :packages, only: %i[new create show edit update destroy]
  end

  # Application routes for booking requests
  resources :booking_requests, only: %i[new show create edit update destroy] do
    member do
      post 'confirm'
    end
  end

  # Application route for public pricing
  get 'pricing', to: 'public#pricing', as: :pricing

  # The root application route
  root 'public#index'
end

app/views/layouts/_header.html.haml
- if flash[:alert]
  .MushakaHeader.MushakaHeader_alert
    %ul
      - flash[:alert].each do |msg|
        %li= msg
- elsif flash[:notice]
  .MushakaHeader.MushakaHeader_notice
    %p= flash[:notice]

app/views/layouts/_nav.html.haml
%nav.MushakaNavbar
  .MushakaNavbar__navbar-header
    %a{ href: '#', id: 'js-navbar-toggle', class: 'MushakaNavbar__navbar-toggle' }
      = icon 'bars'
    %span.MushakaNavbar__navbar-brand PhotogApp
  .MushakaNavbar__navbar-menu
    %ul
      - if signed_in?
        %li
          = link_to I18n.t('navigation.auth.dashboard'), dashboard_path, class: 'MushakaNavbar__navbar-link'
        %li
          = link_to I18n.t('navigation.auth.bookings'), bookings_path, class: 'MushakaNavbar__navbar-link'
        %li
          = link_to I18n.t('navigation.auth.clients'), clients_path, class: 'MushakaNavbar__navbar-link'
        %li
          = link_to I18n.t('navigation.auth.pricing'), package_groups_path, class: 'MushakaNavbar__navbar-link'
        %li
          = link_to I18n.t('navigation.auth.sign_out'), sign_out_path, method: :delete, class: 'MushakaNavbar__navbar-link'
      - else
        %li
          = link_to I18n.t('navigation.public.home'), root_path, class: 'MushakaNavbar__navbar-link'
        %li
          = link_to I18n.t('navigation.public.pricing'), pricing_path, class: 'MushakaNavbar__navbar-link'
        %li
          = link_to I18n.t('navigation.public.book_now'), new_booking_request_path, class: 'MushakaNavbar__navbar-link'
        %li
          = link_to I18n.t('navigation.public.sign_in'), sign_in_path, class: 'MushakaNavbar__navbar-link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{ name: 'viewport', content: 'width=device-width,initial-scale=1.0' }
    %title PhotogApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{ src: 'https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js' }
    %script{ src: 'https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js' }
  %body
    = render 'layouts/nav'
    = render 'layouts/header'
    = yield